language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "8"
  - "10"
install:
  - yarn bootstrap --hoist
script:
  - yarn test
  - yarn lint
notifications:
  email: false
git:
  depth: 5